"""
SensorProvider abstraction (see docs/DATA.md and section 37 of the spec).

REAL SENSOR  -> IoT GATEWAY -> MQTT / REST -> FastAPI -> SensorProcessor -> Digital Twin -> Risk Engine

`SensorProvider` is the interface every data source implements. Only
`DemoSensorProvider` is implemented for the prototype (correlated
synthetic sensor simulation, clearly DEMO/SIMULATED DATA). The stub
classes below show exactly where a real integration would plug in without
touching any downstream code (anomaly detection, health scoring, risk
engine, flood model, etc. all consume `SensorProvider.read()` output only).
"""
from __future__ import annotations

import math
import random
from abc import ABC, abstractmethod
from collections import deque
from dataclasses import dataclass, field

SENSOR_IDS = [
    "water_level_pct",
    "rainfall_mm_hr",
    "reservoir_pressure_kpa",
    "pore_pressure_kpa",
    "concrete_strain",
    "deformation_mm",
    "crack_width_mm",
    "seepage_lps",
    "vibration_g",
    "temperature_c",
]

HISTORY_LEN = 180  # rolling samples kept per sensor (for sparklines + anomaly detection)


class SensorProvider(ABC):
    """Abstract data source for dam sensor readings."""

    @abstractmethod
    def read(self) -> dict[str, float]:
        """Return the current value of every sensor, keyed by sensor_id."""

    @abstractmethod
    def tick(self, dt_min: float, scenario: str) -> dict[str, float]:
        """Advance simulated/real time by dt_min minutes and return new readings."""

    @abstractmethod
    def history(self, sensor_id: str) -> list[float]:
        """Return recent readings for a sensor (used for sparklines/anomaly stats)."""


@dataclass
class _SensorState:
    water_level_pct: float = 62.0
    water_level_m: float = 105.0
    rainfall_mm_hr: float = 3.0
    reservoir_pressure_kpa: float = 870.0
    pore_pressure_kpa: float = 128.0
    concrete_strain: float = 0.00022
    deformation_mm: float = 2.6
    crack_width_mm: float = 0.28
    seepage_lps: float = 7.5
    vibration_g: float = 0.06
    temperature_c: float = 26.0
    sim_minutes: float = 0.0
    breach_stage: int = 0  # 0=none,1=partial,2=major
    breach_onset_min: float = -1.0
    histories: dict[str, deque] = field(default_factory=lambda: {sid: deque(maxlen=HISTORY_LEN) for sid in SENSOR_IDS})


def _clamp(v: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, v))


class DemoSensorProvider(SensorProvider):
    """
    Correlated synthetic dam-sensor simulator.

    THIS IS DEMO / SIMULATED SENSOR DATA. Values are generated by a coupled
    stochastic model (not random-independent noise) so that e.g. rising
    rainfall -> rising reservoir level -> rising pressure -> rising
    deformation/strain -> rising seepage & crack width, matching real dam
    behaviour qualitatively for demonstration purposes.
    """

    def __init__(self, seed: int | None = 42):
        self._rng = random.Random(seed)
        self.state = _SensorState()
        self._prev_snapshot = self._snapshot()
        self._last_change: dict[str, float] = {sid: 0.0 for sid in SENSOR_IDS}

    def _snapshot(self) -> dict[str, float]:
        s = self.state
        return {
            "water_level_pct": s.water_level_pct,
            "water_level_m": s.water_level_m,
            "rainfall_mm_hr": s.rainfall_mm_hr,
            "reservoir_pressure_kpa": s.reservoir_pressure_kpa,
            "pore_pressure_kpa": s.pore_pressure_kpa,
            "concrete_strain": s.concrete_strain,
            "deformation_mm": s.deformation_mm,
            "crack_width_mm": s.crack_width_mm,
            "seepage_lps": s.seepage_lps,
            "vibration_g": s.vibration_g,
            "temperature_c": s.temperature_c,
        }

    def read(self) -> dict[str, float]:
        return self._snapshot()

    def history(self, sensor_id: str) -> list[float]:
        return list(self.state.histories.get(sensor_id, []))

    def trend_pct(self, sensor_id: str) -> float:
        return self._last_change.get(sensor_id, 0.0)

    def breach_stage_label(self) -> str:
        return ["NONE", "PARTIAL", "MAJOR"][self.state.breach_stage]

    # ------------------------------------------------------------------
    def _rainfall_target(self, scenario: str) -> float:
        return {
            "NORMAL": 3.0,
            "HEAVY_RAINFALL": 42.0,
            "RAPID_RESERVOIR_RISE": 30.0,
            "STRUCTURAL_ANOMALY": 12.0,
            "PARTIAL_BREACH": 20.0,
            "MAJOR_BREACH": 25.0,
        }.get(scenario, 3.0)

    def _extra_inflow(self, scenario: str) -> float:
        # extra reservoir-rise forcing (pct/min) beyond rainfall-driven inflow
        return {
            "RAPID_RESERVOIR_RISE": 0.55,
        }.get(scenario, 0.0)

    def _anomaly_forcing(self, scenario: str) -> float:
        # structural anomaly forcing 0..1, drives pore pressure/strain/deformation/seepage
        return {
            "NORMAL": 0.0,
            "HEAVY_RAINFALL": 0.05,
            "RAPID_RESERVOIR_RISE": 0.15,
            "STRUCTURAL_ANOMALY": 0.85,
            "PARTIAL_BREACH": 1.0,
            "MAJOR_BREACH": 1.4,
        }.get(scenario, 0.0)

    def set_breach_stage(self, stage: int) -> None:
        if stage > self.state.breach_stage:
            self.state.breach_onset_min = self.state.sim_minutes
        self.state.breach_stage = stage

    def tick(self, dt_min: float, scenario: str) -> dict[str, float]:
        s = self.state
        r = self._rng
        s.sim_minutes += dt_min
        prev = self._snapshot()

        # rainfall
        target_rain = self._rainfall_target(scenario)
        s.rainfall_mm_hr += (target_rain - s.rainfall_mm_hr) * min(1.0, 0.12 * dt_min) + r.uniform(-0.6, 0.6)
        s.rainfall_mm_hr = _clamp(s.rainfall_mm_hr, 0, 90)

        # water level (reservoir %) - inflow from rainfall + scenario forcing, minus controlled release
        inflow = 0.018 * s.rainfall_mm_hr + self._extra_inflow(scenario)
        outflow = 0.55  # base spillway/managed release, pct/min-equivalent scaled by dt
        breach_outflow = 0.0
        if s.breach_stage == 1:
            breach_outflow = 1.6
        elif s.breach_stage == 2:
            breach_outflow = 4.2

        dlevel = (inflow - 0.12 - breach_outflow) * dt_min + r.uniform(-0.15, 0.15) * dt_min
        new_level = _clamp(s.water_level_pct + dlevel, 8, 100)
        self._last_change["water_level_pct"] = new_level - s.water_level_pct
        s.water_level_pct = new_level
        s.water_level_m = 78 + s.water_level_pct * 0.62

        # reservoir pressure follows water level directly
        target_pressure = 480 + s.water_level_pct * 6.1
        s.reservoir_pressure_kpa += (target_pressure - s.reservoir_pressure_kpa) * min(1.0, 0.3 * dt_min)
        s.reservoir_pressure_kpa += r.uniform(-2, 2)

        anomaly = self._anomaly_forcing(scenario)
        # pore pressure: reservoir level + rainfall infiltration + anomaly forcing
        target_pore = 55 + s.water_level_pct * 1.05 + s.rainfall_mm_hr * 0.5 + anomaly * 95
        s.pore_pressure_kpa += (target_pore - s.pore_pressure_kpa) * min(1.0, 0.22 * dt_min) + r.uniform(-1.5, 1.5)
        s.pore_pressure_kpa = max(20, s.pore_pressure_kpa)

        # concrete strain follows pore pressure + anomaly
        target_strain = 0.00012 + s.pore_pressure_kpa * 0.0000011 + anomaly * 0.00035
        s.concrete_strain += (target_strain - s.concrete_strain) * min(1.0, 0.18 * dt_min) + r.uniform(-0.000006, 0.000006)
        s.concrete_strain = max(0.00005, s.concrete_strain)

        # deformation follows pressure + anomaly, breach accelerates sharply
        target_deform = 1.2 + s.pore_pressure_kpa * 0.014 + anomaly * 6.5 + s.breach_stage * 6.0
        s.deformation_mm += (target_deform - s.deformation_mm) * min(1.0, 0.15 * dt_min) + r.uniform(-0.08, 0.08)
        s.deformation_mm = max(0.2, s.deformation_mm)

        # crack width - tracks a target driven by deformation/anomaly/breach (self-limiting,
        # not an unbounded accumulator), but "heals" far slower than it grows so it stays
        # mostly irreversible on the demo's timescale.
        target_crack = 0.15 + max(0.0, s.deformation_mm - 3.0) * 0.35 + anomaly * 0.6 + s.breach_stage * 1.8
        growth_rate = 0.15 if target_crack > s.crack_width_mm else 0.02
        s.crack_width_mm += (target_crack - s.crack_width_mm) * min(1.0, growth_rate * dt_min) + r.uniform(-0.004, 0.006)
        s.crack_width_mm = max(0.05, s.crack_width_mm)

        # seepage follows pore pressure + crack width
        target_seep = 3.5 + s.pore_pressure_kpa * 0.045 + s.crack_width_mm * 9.5 + s.breach_stage * 14
        s.seepage_lps += (target_seep - s.seepage_lps) * min(1.0, 0.2 * dt_min) + r.uniform(-0.5, 0.5)
        s.seepage_lps = max(0.5, s.seepage_lps)

        # vibration - baseline noise + breach spikes
        base_vib = 0.045 + r.uniform(-0.01, 0.015)
        breach_vib = 0.0
        if s.breach_stage == 1:
            breach_vib = 0.16 + r.uniform(0, 0.08)
        elif s.breach_stage == 2:
            breach_vib = 0.42 + r.uniform(0, 0.15)
        s.vibration_g = max(0.01, base_vib + breach_vib)

        # temperature - slow diurnal cycle
        s.temperature_c = 26.5 + 4.5 * math.sin(s.sim_minutes / 720 * 2 * math.pi) + r.uniform(-0.2, 0.2)

        snap = self._snapshot()
        for sid in SENSOR_IDS:
            s.histories[sid].append(snap[sid])
            self._last_change[sid] = snap[sid] - prev.get(sid, snap[sid])

        return snap


# --- integration-ready stubs (not implemented in the prototype) -----------
class MQTTSensorProvider(SensorProvider):
    """Would subscribe to an MQTT broker fed by an IoT gateway. Not implemented in DEMO MODE."""

    def read(self) -> dict[str, float]:
        raise NotImplementedError("Connect to real MQTT broker to enable this provider")

    def tick(self, dt_min: float, scenario: str) -> dict[str, float]:
        raise NotImplementedError

    def history(self, sensor_id: str) -> list[float]:
        raise NotImplementedError


class RestPollSensorProvider(SensorProvider):
    """Would poll a REST endpoint exposed by an on-site IoT gateway. Not implemented in DEMO MODE."""

    def read(self) -> dict[str, float]:
        raise NotImplementedError("Configure gateway REST endpoint to enable this provider")

    def tick(self, dt_min: float, scenario: str) -> dict[str, float]:
        raise NotImplementedError

    def history(self, sensor_id: str) -> list[float]:
        raise NotImplementedError


class SerialSensorProvider(SensorProvider):
    """Would read directly from a serial/RS-485 data logger. Not implemented in DEMO MODE."""

    def read(self) -> dict[str, float]:
        raise NotImplementedError("Attach serial data logger to enable this provider")

    def tick(self, dt_min: float, scenario: str) -> dict[str, float]:
        raise NotImplementedError

    def history(self, sensor_id: str) -> list[float]:
        raise NotImplementedError
